# Generated by Django 3.0.7 on 2020-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0007_auto_20200629_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
