# Generated by Django 3.0.7 on 2020-06-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0011_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='description',
        ),
    ]
