# Generated by Django 3.0.7 on 2020-06-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0012_auto_20200629_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='important',
            new_name='urgent',
        ),
    ]
